#!/usr/bin/env python3

from os import system
from sys import stderr

if __name__ == '__main__':
    try:
        # Sanity check.
        # Fail if we don't have Pelican installed.
        import pelican

        system("pelican --autoreload --listen")

    except ImportError:
        stderr.write("Please install Pelican.\n")
        exit(1)
